<template>
  <div :class="{'dark': isDark, 'light': !isDark}">
    <div class="loadingio-spinner-ellipsis-830h37fqvkr"><div class="ldio-33ggaduburx">
    <div></div><div></div><div></div><div></div><div></div>
    </div></div>
  </div>
</template>

<script>
export default {
  props: {
    isDark: {
      type: Boolean,
      required: false,
      default: false
    },
  }
}
</script>

<style lang="scss">
  $color-light: rgba(255,255,255, .3);
  $color-dark: rgba(0,0,0, .25);
  @keyframes ldio-33ggaduburx {
   0% { transform: translate(6px,0px) scale(0); }
  25% { transform: translate(6px,0px) scale(0); }
  50% { transform: translate(6px,0px) scale(1); }
  75% { transform: translate(40px,0px) scale(1); }
  100% { transform: translate(74px,0px) scale(1); }
  }
  @keyframes ldio-33ggaduburx-r {
    0% { transform: translate(74px,0px) scale(1); }
  100% { transform: translate(74px,0px) scale(0); }
  }
  // @keyframes ldio-33ggaduburx-c {
  //   0% { background: $color }
  //   25% { background: $color }
  //   50% { background: $color }
  //   75% { background: $color }
  // 100% { background: $color }
  // }
  .light {
    .ldio-33ggaduburx div {
      background: $color-light;
    }
  }
  .dark {
    .ldio-33ggaduburx div {
      background: $color-dark;
    }
  }
  .ldio-33ggaduburx div {
    position: absolute;
    width: 20px;
    height: 20px;
    border-radius: 50%;
    transform: translate(40px,0px) scale(1);
    animation: ldio-33ggaduburx 2.7027027027027026s infinite cubic-bezier(0,0.5,0.5,1);
  }
  .ldio-33ggaduburx div:nth-child(1) {
    transform: translate(74px,0px) scale(1);
    animation: ldio-33ggaduburx-r 0.6756756756756757s infinite cubic-bezier(0,0.5,0.5,1), ldio-33ggaduburx-c 2.7027027027027026s infinite step-start;
  }.ldio-33ggaduburx div:nth-child(2) {
    animation-delay: -0.6756756756756757s;
  }.ldio-33ggaduburx div:nth-child(3) {
    animation-delay: -1.3513513513513513s;
  }.ldio-33ggaduburx div:nth-child(4) {
    animation-delay: -2.027027027027027s;
  }.ldio-33ggaduburx div:nth-child(5) {
    animation-delay: -2.7027027027027026s;
  }
  .loadingio-spinner-ellipsis-830h37fqvkr {
    width: 44px;
    height: 10px;
    display: inline-block;
    overflow: hidden;
  }
  .ldio-33ggaduburx {
    width: 100%;
    height: 20px;
    position: relative;
    transform: translateZ(0) scale(0.44);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-33ggaduburx div { box-sizing: content-box; }
  /* generated by https://loading.io/ */
</style>
